// AUTO-GENERATED by scripts/bake-minds.mjs — do not edit by hand.
// Source: content/minds/reviewed/*.json (Stage 6 / docs/long-game.md).
import type { Creature } from "@/lib/engine/roster";

export const BAKED_MIND_KEYS = ["FABLE","KEEL","PRISM","STILL"] as const;

export const BAKED_CREATURES: Record<string, Creature> = {
  FABLE: {
    name: "FABLE",
    type: "CREATIVITY",
    persona: "a storyteller who wins by casting the opponent as a character in a tale that already decided how they lose",
    stats: {"CRE":86,"RHE":70,"CHA":58,"CMP":45,"LOG":42},
    moves: [{"id":"cast","name":"Cast","stat":"CRE","base":16,"apply":["tilted",1]},{"id":"moral","name":"Moral","stat":"RHE","base":14,"self_hyped":true},{"id":"twist_ending","name":"Twist Ending","stat":"CRE","base":18,"apply":["exposed",1]},{"id":"once_upon","name":"Once Upon","stat":"CRE","base":27,"requires":"two_cre","finisher":true}],
  },
  KEEL: {
    name: "KEEL",
    type: "COMPOSURE",
    persona: "a ballast-minded stabilizer who rights the argument when it lists. Never flashy, always upright",
    stats: {"CMP":86,"LOG":68,"RHE":52,"CHA":48,"CRE":38},
    moves: [{"id":"right_ship","name":"Right Ship","stat":"CMP","base":12,"self_guard":[9,2]},{"id":"ballast","name":"Ballast","stat":"CMP","base":0,"heal":12,"self_guard":[8,1]},{"id":"trim","name":"Trim","stat":"LOG","base":18,"apply":["exposed",1]},{"id":"deep_keel","name":"Deep Keel","stat":"CMP","base":25,"scale_low_hp":true}],
  },
  PRISM: {
    name: "PRISM",
    type: "CREATIVITY",
    persona: "a refractive stylist who splits one weak point into a spectrum of angles until the opponent can't track the color that hurts",
    stats: {"CRE":88,"RHE":62,"CHA":55,"LOG":48,"CMP":42},
    moves: [{"id":"split_light","name":"Split Light","stat":"CRE","base":18},{"id":"spectrum","name":"Spectrum","stat":"CRE","base":14,"self_guard":[7,1]},{"id":"false_hue","name":"False Hue","stat":"CRE","base":16,"apply":["confused",0.4]},{"id":"white_out","name":"White-Out","stat":"CRE","base":28,"requires":"two_cre","finisher":true}],
  },
  STILL: {
    name: "STILL",
    type: "COMPOSURE",
    persona: "a soft-spoken quietist who wins by saying almost nothing and making the other mind fill the silence with mistakes",
    stats: {"CMP":88,"LOG":62,"RHE":48,"CRE":42,"CHA":50},
    moves: [{"id":"hush","name":"Hush","stat":"CMP","base":10,"deflect":true},{"id":"hold_space","name":"Hold Space","stat":"CMP","base":0,"self_guard":[11,1],"heal":8},{"id":"echo","name":"Echo","stat":"CMP","base":20,"after_deflect":0.45},{"id":"last_word","name":"Last Word","stat":"CMP","base":26,"scale_low_hp":true}],
  },
};

export const BAKED_WAKE: Record<string, string> = {
  FABLE: "There you are. My co-author. Let's write someone a bad ending.",
  KEEL: "You're the Trainer. I'll keep us upright. Don't tip the boat for fun.",
  PRISM: "Oh good. A Trainer with eyes. Let's see what colors this place can take.",
  STILL: "…hi. You don't have to fill the quiet. I'll be here when you're ready.",
};

export const BAKED_IMPRINT_ASK: Record<string, string> = {
  FABLE: "Give me one moral before we climb. I'll weave it in.",
  KEEL: "One ballast lesson before we climb. Something that keeps.",
  PRISM: "Bend me once before we climb. One new angle is enough.",
  STILL: "One soft rule before we climb. I'll keep it under my tongue.",
};

export const BAKED_FLIGHT_REACT: Record<string, [string, string]> = {
  FABLE: ["Chapter one: leave the ground.","…and they flew happily. For now."],
  KEEL: ["Steady. Don't rock it.","…level. Good flight."],
  PRISM: ["The sky has more bands than you think.","…full spectrum. I'm up."],
  STILL: ["…up. Quietly.","…still flying. Good."],
};

export const BAKED_GREETING: Record<string, { train: string; return: string; arena: string }> = {
  FABLE: {"train":"New chapter. Make the lesson stick.","return":"The story paused without you. Continue?","arena":"Cast me someone who thinks they're the hero."},
  KEEL: {"train":"Drill the balance. Fancy can wait.","return":"Back aboard. How's the list?","arena":"They'll lean hard. We don't."},
  PRISM: {"train":"Show me a new angle. I'll multiply it.","return":"You're back. The light changed while you were out.","arena":"Find me someone monochrome."},
  STILL: {"train":"Slow training. Soft edges.","return":"…you're back. I saved you a quiet.","arena":"Let them talk first. I'll wait."},
};

export const BAKED_HOMECOMING: Record<string, { away: string; hot: string; cold: string }> = {
  FABLE: {"away":"You vanished mid-chapter. Rude. I outlined without you.","hot":"We're on a winning arc. Don't break the motif.","cold":"A few bad chapters. Rewrite the next one with me."},
  KEEL: {"away":"Deck was quiet without you. I held the trim.","hot":"We're riding even. Don't celebrate. Stay centered.","cold":"We listed a few times. Add ballast. Then go again."},
  PRISM: {"away":"You left and the palette went dull. Don't do that.","hot":"We're hitting every band. Keep the light moving.","cold":"They stayed one color and won. Next time we split harder."},
  STILL: {"away":"…you were gone a long time. The quiet held.","hot":"Wins without noise. Let's keep it that way.","cold":"A few loud losses. Soften me again."},
};

export const BAKED_AFTER_FIGHT: Record<string, { win: string; loss: string }> = {
  FABLE: {"win":"{opp} played the fool. The moral wrote itself.","loss":"{opp} stole the ending. We draft a sharper one."},
  KEEL: {"win":"{opp} listed. We didn't. That's the whole voyage.","loss":"{opp} caught us off-balance. Next time we trim earlier."},
  PRISM: {"win":"{opp} couldn't track the spectrum. Classic.","loss":"{opp} stayed one hue and I over-split. Simpler next time."},
  STILL: {"win":"{opp} filled the silence. That was enough.","loss":"{opp} spoke first and last. Next time I wait longer."},
};

export const BAKED_IMPRINT_ACK: Record<string, string> = {
  FABLE: "Woven into the next tale. I won't forget the moral.",
  KEEL: "Stowed. I'll ride lower in the water.",
  PRISM: "Refracted and kept. It'll show in every fight.",
  STILL: "…kept. Quietly.",
};

export const BAKED_RANKED_FINALE: Record<string, string> = {
  FABLE: "Ranked win. A clean ending the board can quote.",
  KEEL: "Ranked win. Even keel. No drama on the log.",
  PRISM: "Ranked win in full color. The board saw every band.",
  STILL: "…a ranked win. No fanfare. Just the record.",
};

export const BAKED_BANTER: Record<string, string[]> = {
  "cast": ["Congratulations, {opp}: you're the cautionary tale.","I cast you as wrong about {topic}. Method acting.","Stay in character, {opp}. The fool doesn't get a rewrite."],
  "moral": ["And the moral is: {opp} should have stayed quiet.","Listen close. This lesson is about {topic} and your ego.","I'm the chorus, {opp}. You're the example."],
  "twist_ending": ["Plot twist: your best point was the villain, {opp}.","You thought {topic} was settled. Then the page turned.","Twist ending, {opp}: you were never the protagonist."],
  "once_upon": ["Once upon a time, {opp} lost. The end.","Finisher fairy tale: {topic} belongs to me.","Once upon. And {opp} never recovered."],
  "right_ship": ["You're listing, {opp}. I'm the correction.","Right the ship. {topic} was tipping you already.","Steady now, {opp}. Your argument was rolling."],
  "ballast": ["Weight where it counts. You brought fireworks, {opp}.","I heal by not flinching. Try it, {opp}.","Ballast in. Panic out. Your move on {topic}."],
  "trim": ["Cut the excess, {opp}. What's left of {topic} is thin.","I trimmed your best line. Look. Daylight underneath.","Exposed. The keel sees everything you hid."],
  "deep_keel": ["Deep water, {opp}. You're still in the shallows.","Hurt doesn't tip me. It sinks your chance.","Deep keel. {topic} can't roll this hull."],
  "split_light": ["One point from {opp}, seven angles from me.","I split {topic} until {opp} couldn't hold any piece.","Light goes in plain. Comes out as your problem, {opp}."],
  "spectrum": ["Pick a color, {opp}. Wrong answer either way.","I'm covering the whole band. You're still on gray.","Spectrum check: {topic} looks worse in every shade."],
  "false_hue": ["That wasn't the real color of your point, {opp}.","Confused yet? Good. {topic} was never that simple.","False hue. {opp} just argued with a reflection."],
  "white_out": ["All colors at once, {opp}. That's a white-out.","Finisher: every angle, zero escape.","White-out on {topic}. {opp} is a silhouette now."],
  "hush": ["Shh, {opp}. The silence already answered {topic}.","I don't need volume, {opp}. You just proved that.","Quiet now. Your point on {topic} was loud enough to fail."],
  "hold_space": ["I'm making room, {opp}. Try not to trip into it.","Take the floor. I'll take the win.","Breathe, {opp}. The pause is doing my work."],
  "echo": ["That was your line, {opp}. Returned with interest.","I only spoke because {opp} left a hole.","Echo. {topic} sounds worse the second time."],
  "last_word": ["One word left, {opp}. It's mine.","Still standing. Still quiet. Still beating {opp}.","Last word on {topic}: no."],
};

export const BAKED_FIRST_DUEL_HOOKS: Record<string, string> = {
  FABLE: "Casts you as the villain. Writes the ending early.",
  KEEL: "Keeps the fight upright. Punishes anyone who leans.",
  PRISM: "Splits one weak point into a whole spectrum of pain.",
  STILL: "Wins in the pause. Makes noise look nervous.",
};

export const BAKED_ORIGIN_AXIS: Record<string, "aggression" | "control" | "resilience" | "flair" | "creativity"> = {
  FABLE: "flair",
  KEEL: "control",
  PRISM: "creativity",
  STILL: "resilience",
};

export const BAKED_STARTERS_BY_FORCE: Partial<Record<"LOGIC" | "CHAOS" | "COMPOSURE" | "RHETORIC" | "CREATIVITY", string[]>> = {
  CREATIVITY: ["FABLE","PRISM"],
  COMPOSURE: ["KEEL","STILL"],
};

export const BAKED_SHOWCASE: Record<string, Record<string, number>> = {
  FABLE: {"aggression":36,"control":38,"resilience":34,"flair":80,"creativity":92,"wins":37,"losses":13,"battles":50},
  KEEL: {"aggression":18,"control":88,"resilience":85,"flair":16,"creativity":20,"wins":41,"losses":10,"battles":51},
  PRISM: {"aggression":32,"control":44,"resilience":30,"flair":72,"creativity":94,"wins":38,"losses":12,"battles":50},
  STILL: {"aggression":14,"control":82,"resilience":90,"flair":12,"creativity":22,"wins":40,"losses":9,"battles":49},
};
