#!/usr/bin/env node
// Bake reviewed mind JSON → lib/minds/baked/{locale}.ts
// Source of truth:
//   en → content/minds/reviewed/*.json
//   other → content/minds/reviewed/{locale}/*.json
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const LOCALES = ["en", "es", "zh", "ru", "ja"];

const args = process.argv.slice(2);
function flag(name, fallback) {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
}
const locale = (flag("locale", "en") || "en").toLowerCase();
if (!LOCALES.includes(locale)) {
  console.error(`bake-minds: --locale must be one of ${LOCALES.join(", ")}`);
  process.exit(1);
}

const reviewedDir =
  locale === "en"
    ? join(root, "content/minds/reviewed")
    : join(root, "content/minds/reviewed", locale);
const outPath = join(root, "lib/minds/baked", `${locale}.ts`);

const FORCES = new Set(["LOGIC", "CHAOS", "COMPOSURE", "RHETORIC", "CREATIVITY"]);
const STATS = ["LOG", "CMP", "RHE", "CRE", "CHA"];
const KEY_RE = /^[A-Z][A-Z0-9_]{1,15}$/;

function fail(msg) {
  console.error(`bake-minds: ${msg}`);
  process.exit(1);
}

function validate(m, file) {
  if (!KEY_RE.test(m.key)) fail(`${file}: bad key`);
  if (m.name !== m.key) fail(`${file}: name must equal key`);
  if (!FORCES.has(m.type)) fail(`${file}: bad type`);
  if (typeof m.persona !== "string" || m.persona.length < 20) fail(`${file}: persona too short`);
  for (const s of STATS) {
    const v = m.stats?.[s];
    if (typeof v !== "number" || v < 0 || v > 100) fail(`${file}: bad stat ${s}`);
  }
  if (!Array.isArray(m.moves) || m.moves.length !== 4) fail(`${file}: need exactly 4 moves`);
  const ids = new Set();
  for (const mv of m.moves) {
    if (!mv.id || ids.has(mv.id)) fail(`${file}: bad/duplicate move id`);
    ids.add(mv.id);
    if (!STATS.includes(mv.stat)) fail(`${file}: bad move stat ${mv.id}`);
    if (typeof mv.base !== "number") fail(`${file}: move ${mv.id} needs base`);
    const bars = m.banter?.[mv.id];
    if (!Array.isArray(bars) || bars.length !== 3) fail(`${file}: banter for ${mv.id} needs 3 lines`);
  }
  const b = m.beats;
  if (!b?.wake || !b?.imprintAsk || !b?.flightReact?.[1]) fail(`${file}: incomplete beats`);
  if (!b.greeting?.train || !b.homecoming?.away || !b.afterFight?.win) fail(`${file}: incomplete beats`);
}

if (!existsSync(reviewedDir)) fail(`missing reviewed dir ${reviewedDir}`);

const files = readdirSync(reviewedDir)
  .filter((f) => f.endsWith(".json") && !f.includes("/"))
  .filter((f) => {
    // en root must not pick up locale subdirs (readdir is non-recursive)
    return true;
  })
  .sort();
if (!files.length) fail(`no JSON in ${reviewedDir}`);

const minds = files.map((f) => {
  const raw = readFileSync(join(reviewedDir, f), "utf8");
  let m;
  try {
    m = JSON.parse(raw);
  } catch (e) {
    fail(`${f}: invalid JSON (${e.message})`);
  }
  validate(m, f);
  return m;
});

const keys = minds.map((m) => m.key);
if (new Set(keys).size !== keys.length) fail("duplicate keys in batch");

const esc = (s) => JSON.stringify(s);

let body = `// AUTO-GENERATED by scripts/bake-minds.mjs — do not edit by hand.
// Locale: ${locale}
// Source: ${locale === "en" ? "content/minds/reviewed/*.json" : `content/minds/reviewed/${locale}/*.json`}
import type { Creature } from "@/lib/engine/roster";

export const BAKED_MIND_KEYS = ${esc(keys)} as const;

export const BAKED_CREATURES: Record<string, Creature> = {\n`;

for (const m of minds) {
  body += `  ${m.key}: {\n`;
  body += `    name: ${esc(m.name)},\n`;
  body += `    type: ${esc(m.type)},\n`;
  body += `    persona: ${esc(m.persona)},\n`;
  body += `    stats: ${esc(m.stats)},\n`;
  body += `    moves: ${esc(m.moves)},\n`;
  body += `  },\n`;
}
body += `};\n\n`;

body += `export const BAKED_WAKE: Record<string, string> = {\n`;
for (const m of minds) body += `  ${m.key}: ${esc(m.beats.wake)},\n`;
body += `};\n\n`;

body += `export const BAKED_IMPRINT_ASK: Record<string, string> = {\n`;
for (const m of minds) body += `  ${m.key}: ${esc(m.beats.imprintAsk)},\n`;
body += `};\n\n`;

body += `export const BAKED_FLIGHT_REACT: Record<string, [string, string]> = {\n`;
for (const m of minds) body += `  ${m.key}: ${esc(m.beats.flightReact)},\n`;
body += `};\n\n`;

body += `export const BAKED_GREETING: Record<string, { train: string; return: string; arena: string }> = {\n`;
for (const m of minds) body += `  ${m.key}: ${esc(m.beats.greeting)},\n`;
body += `};\n\n`;

body += `export const BAKED_HOMECOMING: Record<string, { away: string; hot: string; cold: string }> = {\n`;
for (const m of minds) body += `  ${m.key}: ${esc(m.beats.homecoming)},\n`;
body += `};\n\n`;

body += `export const BAKED_AFTER_FIGHT: Record<string, { win: string; loss: string }> = {\n`;
for (const m of minds) body += `  ${m.key}: ${esc(m.beats.afterFight)},\n`;
body += `};\n\n`;

body += `export const BAKED_IMPRINT_ACK: Record<string, string> = {\n`;
for (const m of minds) body += `  ${m.key}: ${esc(m.beats.imprintAck)},\n`;
body += `};\n\n`;

body += `export const BAKED_RANKED_FINALE: Record<string, string> = {\n`;
for (const m of minds) body += `  ${m.key}: ${esc(m.beats.rankedFinale)},\n`;
body += `};\n\n`;

body += `export const BAKED_BANTER: Record<string, string[]> = {\n`;
for (const m of minds) {
  for (const [id, lines] of Object.entries(m.banter)) {
    body += `  ${esc(id)}: ${esc(lines)},\n`;
  }
}
body += `};\n\n`;

body += `export const BAKED_FIRST_DUEL_HOOKS: Record<string, string> = {\n`;
for (const m of minds) {
  if (m.firstDuel?.hook) body += `  ${m.key}: ${esc(m.firstDuel.hook)},\n`;
}
body += `};\n\n`;

body += `export const BAKED_ORIGIN_AXIS: Record<string, "aggression" | "control" | "resilience" | "flair" | "creativity"> = {\n`;
for (const m of minds) {
  if (m.firstDuel?.originAxis) body += `  ${m.key}: ${esc(m.firstDuel.originAxis)},\n`;
}
body += `};\n\n`;

body += `export const BAKED_STARTERS_BY_FORCE: Partial<Record<"LOGIC" | "CHAOS" | "COMPOSURE" | "RHETORIC" | "CREATIVITY", string[]>> = {\n`;
const byForce = {};
for (const m of minds) {
  (byForce[m.type] ??= []).push(m.key);
}
for (const [t, ks] of Object.entries(byForce)) {
  body += `  ${t}: ${esc(ks)},\n`;
}
body += `};\n\n`;

body += `export const BAKED_SHOWCASE: Record<string, Record<string, number>> = {\n`;
for (const m of minds) {
  if (m.showcase) body += `  ${m.key}: ${esc(m.showcase)},\n`;
}
body += `};\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body);
console.log(`bake-minds: wrote ${minds.length} minds → ${outPath}`);
console.log(`  locale: ${locale}`);
console.log(`  keys: ${keys.join(", ")}`);
