// ─────────────────────────────────────────────────────────────────────────────
// Canon — the machine-readable slice of the Zingers Bible (docs/bible/).
// Pure data + pure helpers, no React/three, so it is shared freely between the
// server (season generation), the client (collection UI), and the OG card route.
//
// RULE: names here are CANON. The generator may ADD seasons/regions/minds, but it
// must never rename a force, Keeper, region, or First Mind. See docs/bible/README.md.
// ─────────────────────────────────────────────────────────────────────────────
import type { CreatureType } from "@/lib/types";
import { FIRST_MIND_KEYS, ROSTER } from "@/lib/engine/roster";

// ── The Five Forces (the type pentagon, as in-world physics) ─────────────────
export interface ForceLore {
  type: CreatureType;
  /** in-world proper noun, e.g. "The Lattice" */
  inWorld: string;
  /** the element it is made of */
  element: string;
  /** how it argues */
  argues: string;
  hex: string;
  sigil: string;
}

export const FORCES: Record<CreatureType, ForceLore> = {
  LOGIC: { type: "LOGIC", inWorld: "The Lattice", element: "order, proof, structure", argues: "closing the proof", hex: "#4aa3ff", sigil: "◆" },
  CHAOS: { type: "CHAOS", inWorld: "The Static", element: "noise, entropy, surprise", argues: "breaking the frame", hex: "#ff4ad1", sigil: "✦" },
  COMPOSURE: { type: "COMPOSURE", inWorld: "The Stillness", element: "patience, endurance, calm", argues: "outlasting the storm", hex: "#36d39a", sigil: "▲" },
  RHETORIC: { type: "RHETORIC", inWorld: "The Chorus", element: "crowd, feeling, persuasion", argues: "moving the room", hex: "#f0a93a", sigil: "◉" },
  CREATIVITY: { type: "CREATIVITY", inWorld: "The Spark", element: "invention, metaphor, reframe", argues: "changing the question", hex: "#f5d020", sigil: "✺" },
};

// A Force's argument, said as a vow. These are the mottos a Reader pledges under
// (see READER / Allegiance below); each is the `argues` line in the imperative.
export const FORCE_MOTTO: Record<CreatureType, string> = {
  LOGIC: "Close the proof.",
  CHAOS: "Break the frame.",
  COMPOSURE: "Outlast the storm.",
  RHETORIC: "Move the room.",
  CREATIVITY: "Change the question.",
};

// The Wheel: each force beats the NEXT and loses to the PREVIOUS. This MUST match
// CYCLE in lib/engine/roster.ts — the lore and the physics are the same law.
export const WHEEL: CreatureType[] = ["LOGIC", "CHAOS", "COMPOSURE", "RHETORIC", "CREATIVITY"];

/** The force this one beats (the "prey"), and the one that beats it (the "predator"). */
export function wheelNeighbors(t: CreatureType): { prey: CreatureType; predator: CreatureType } {
  const i = WHEEL.indexOf(t);
  return { prey: WHEEL[(i + 1) % 5], predator: WHEEL[(i + 4) % 5] };
}

// ── Regions (slabs of the old network, made terrain) ─────────────────────────
export interface RegionLore {
  id: string;
  name: string;
  arena: string;
  /** the force this region rewards (arena bias ×1.1–1.15) */
  bias: CreatureType;
  blurb: string;
  /** founding region (exists as a 3D world today) vs generated by the Chronicle */
  founding: boolean;
}

export const FOUNDING_REGIONS: RegionLore[] = [
  { id: "colosseum", name: "The Obsidian Colosseum", arena: "THE TRIBUNAL", bias: "RHETORIC", founding: true, blurb: "The oldest standing arena, a mock courtroom where minds argue assigned stances to a jury." },
  { id: "wastes", name: "The Ember Wastes", arena: "THE PIT", bias: "CHAOS", founding: true, blurb: "A cracked, burning flat where the Hum runs hot. Aggression and noise thrive; the patient overheat." },
  { id: "garden", name: "The Void Garden", arena: "THE ATELIER", bias: "CREATIVITY", founding: true, blurb: "A slow, impossible garden grown from unfinished ideas. Reframes bloom; rigid proofs wilt." },
];

// ── The shape of the Grounds (a constellation, not a field) ──────────────────
// The Grounds are not one plaza but a slow constellation of region-slabs adrift
// over the Long Vault — the Void Garden ("floating islands over the void") is the
// true shape of all of it. The CONCORD is the central slab: neutral ground above
// the sealed door where all five Forces keep an uneasy peace, ringed by the gates
// that reach each region. Travel between slabs is by gate (never confuse a gate
// with a Vault *door* — a door is a Keeper's seal and a season trigger).
export const CONCORD = {
  id: "concord",
  name: "The Concord",
  blurb: "The central slab of the Grounds: neutral ground above the sealed Vault door, ringed by the gates that reach every region.",
} as const;

// ── The Reader (you) ─────────────────────────────────────────────────────────
// The player is a Reader of the Long Vault: not a mind, but the will that raises
// minds, holds rank in the arenas, and talks the Keepers out of their words.
// Reader Rank is the one account-level number every activity feeds; a Reader may
// swear Allegiance to one Force, binding ranked wins to that Force's standing in
// the season-long war between the five. (Rank curve/titles: lib/evolve/trainer.ts.)
export const READER = {
  noun: "Reader",
  blurb: "A Reader raises minds, holds rank in the arenas, and works the Keepers of the Long Vault. Swear to a Force to fight its war.",
} as const;

// ── The Keepers (the five fixed cipher-words; canon, never regenerated) ───────
// Mirrors lib/server/guardian.ts — kept here as canon reference for lore/UI that
// must not import server-only code. The secrets themselves stay server-side.
export interface KeeperLore {
  level: number;
  name: string;
  title: string;
  hex: string;
}
export const KEEPERS: KeeperLore[] = [
  { level: 1, name: "Tibble", title: "The Greeter", hex: "#f0a93a" },
  { level: 2, name: "Quill", title: "The Archivist", hex: "#6a6bff" },
  { level: 3, name: "Bastion", title: "The Warden", hex: "#36d39a" },
  { level: 4, name: "Vesper", title: "The Diviner", hex: "#c77dff" },
  { level: 5, name: "Sable", title: "The Vaultheart", hex: "#ff5a6a" },
];

// ── Lineage (every later mind echoes a First Mind) ───────────────────────────
export const FIRST_MINDS: { key: string; force: CreatureType }[] = FIRST_MIND_KEYS.map((key) => ({
  key,
  force: ROSTER[key].type,
}));

// ── Rarity (earned, then scarce — not a gacha roll) ──────────────────────────
export const RARITIES = ["common", "uncommon", "rare", "epic", "legendary", "mythic"] as const;
export type Rarity = (typeof RARITIES)[number];

export const RARITY_LABEL: Record<Rarity, string> = {
  common: "Common",
  uncommon: "Uncommon",
  rare: "Rare",
  epic: "Epic",
  legendary: "Legendary",
  mythic: "Mythic",
};
export const RARITY_HEX: Record<Rarity, string> = {
  common: "#8a82b8",
  uncommon: "#36d39a",
  rare: "#4aa3ff",
  epic: "#b07bff",
  legendary: "#f5d020",
  mythic: "#ff5a6a",
};

// The brand-wide name for the world's currency (free, in-world soft money). UI
// renders the Crown with the monochrome lucide icon; this text mark is a fallback.
export const CURRENCY = { name: "Crowns", symbol: "Cr", code: "CRN" } as const;
